# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import heraclitus_pb2 as heraclitus__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in heraclitus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HeraclitusStub(object):
    """gRPC surface (§3.14): Append, Query, Recall, Subscribe(tail), Snapshot,
    Admin{rebuild, demote, stats}.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.unary_unary(
                '/heraclitus.v1.Heraclitus/Append',
                request_serializer=heraclitus__pb2.AppendRequest.SerializeToString,
                response_deserializer=heraclitus__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/heraclitus.v1.Heraclitus/Query',
                request_serializer=heraclitus__pb2.QueryRequest.SerializeToString,
                response_deserializer=heraclitus__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/heraclitus.v1.Heraclitus/Recall',
                request_serializer=heraclitus__pb2.RecallRequest.SerializeToString,
                response_deserializer=heraclitus__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/heraclitus.v1.Heraclitus/Subscribe',
                request_serializer=heraclitus__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=heraclitus__pb2.EventMessage.FromString,
                _registered_method=True)
        self.Snapshot = channel.unary_unary(
                '/heraclitus.v1.Heraclitus/Snapshot',
                request_serializer=heraclitus__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=heraclitus__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.Admin = channel.unary_unary(
                '/heraclitus.v1.Heraclitus/Admin',
                request_serializer=heraclitus__pb2.AdminRequest.SerializeToString,
                response_deserializer=heraclitus__pb2.AdminResponse.FromString,
                _registered_method=True)


class HeraclitusServicer(object):
    """gRPC surface (§3.14): Append, Query, Recall, Subscribe(tail), Snapshot,
    Admin{rebuild, demote, stats}.
    """

    def Append(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Snapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Admin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeraclitusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Append': grpc.unary_unary_rpc_method_handler(
                    servicer.Append,
                    request_deserializer=heraclitus__pb2.AppendRequest.FromString,
                    response_serializer=heraclitus__pb2.AppendResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=heraclitus__pb2.QueryRequest.FromString,
                    response_serializer=heraclitus__pb2.QueryResponse.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=heraclitus__pb2.RecallRequest.FromString,
                    response_serializer=heraclitus__pb2.QueryResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=heraclitus__pb2.SubscribeRequest.FromString,
                    response_serializer=heraclitus__pb2.EventMessage.SerializeToString,
            ),
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=heraclitus__pb2.SnapshotRequest.FromString,
                    response_serializer=heraclitus__pb2.SnapshotResponse.SerializeToString,
            ),
            'Admin': grpc.unary_unary_rpc_method_handler(
                    servicer.Admin,
                    request_deserializer=heraclitus__pb2.AdminRequest.FromString,
                    response_serializer=heraclitus__pb2.AdminResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heraclitus.v1.Heraclitus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heraclitus.v1.Heraclitus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Heraclitus(object):
    """gRPC surface (§3.14): Append, Query, Recall, Subscribe(tail), Snapshot,
    Admin{rebuild, demote, stats}.
    """

    @staticmethod
    def Append(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heraclitus.v1.Heraclitus/Append',
            heraclitus__pb2.AppendRequest.SerializeToString,
            heraclitus__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heraclitus.v1.Heraclitus/Query',
            heraclitus__pb2.QueryRequest.SerializeToString,
            heraclitus__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heraclitus.v1.Heraclitus/Recall',
            heraclitus__pb2.RecallRequest.SerializeToString,
            heraclitus__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/heraclitus.v1.Heraclitus/Subscribe',
            heraclitus__pb2.SubscribeRequest.SerializeToString,
            heraclitus__pb2.EventMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heraclitus.v1.Heraclitus/Snapshot',
            heraclitus__pb2.SnapshotRequest.SerializeToString,
            heraclitus__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Admin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heraclitus.v1.Heraclitus/Admin',
            heraclitus__pb2.AdminRequest.SerializeToString,
            heraclitus__pb2.AdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
