# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heraclitus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'heraclitus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10heraclitus.proto\x12\rheraclitus.v1\"\xf2\x01\n\rAppendRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x0b\n\x03hyp\x18\x05 \x03(\x02\x12\x0b\n\x03sph\x18\x06 \x03(\x02\x12\x0b\n\x03\x65uc\x18\x07 \x03(\x02\x12\x36\n\x05\x61ttrs\x18\x08 \x03(\x0b\x32\'.heraclitus.v1.AppendRequest.AttrsEntry\x12\x0f\n\x07parents\x18\t \x03(\t\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1d\n\x0e\x41ppendResponse\x12\x0b\n\x03lsn\x18\x01 \x01(\x04\"\x1b\n\x0cQueryRequest\x12\x0b\n\x03gql\x18\x01 \x01(\t\"\x1d\n\rQueryResponse\x12\x0c\n\x04json\x18\x01 \x01(\t\"(\n\rRecallRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\r\"$\n\x10SubscribeRequest\x12\x10\n\x08\x66rom_lsn\x18\x01 \x01(\x04\"1\n\x0c\x45ventMessage\x12\x0b\n\x03lsn\x18\x01 \x01(\x04\x12\x14\n\x0c\x65pisode_json\x18\x02 \x01(\t\"\x11\n\x0fSnapshotRequest\"\x1f\n\x10SnapshotResponse\x12\x0b\n\x03lsn\x18\x01 \x01(\x04\"\'\n\x0c\x41\x64minRequest\x12\n\n\x02op\x18\x01 \x01(\t\x12\x0b\n\x03\x61rg\x18\x02 \x01(\t\",\n\rAdminResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbb\x03\n\nHeraclitus\x12\x45\n\x06\x41ppend\x12\x1c.heraclitus.v1.AppendRequest\x1a\x1d.heraclitus.v1.AppendResponse\x12\x42\n\x05Query\x12\x1b.heraclitus.v1.QueryRequest\x1a\x1c.heraclitus.v1.QueryResponse\x12\x44\n\x06Recall\x12\x1c.heraclitus.v1.RecallRequest\x1a\x1c.heraclitus.v1.QueryResponse\x12K\n\tSubscribe\x12\x1f.heraclitus.v1.SubscribeRequest\x1a\x1b.heraclitus.v1.EventMessage0\x01\x12K\n\x08Snapshot\x12\x1e.heraclitus.v1.SnapshotRequest\x1a\x1f.heraclitus.v1.SnapshotResponse\x12\x42\n\x05\x41\x64min\x12\x1b.heraclitus.v1.AdminRequest\x1a\x1c.heraclitus.v1.AdminResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heraclitus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPENDREQUEST_ATTRSENTRY']._loaded_options = None
  _globals['_APPENDREQUEST_ATTRSENTRY']._serialized_options = b'8\001'
  _globals['_APPENDREQUEST']._serialized_start=36
  _globals['_APPENDREQUEST']._serialized_end=278
  _globals['_APPENDREQUEST_ATTRSENTRY']._serialized_start=234
  _globals['_APPENDREQUEST_ATTRSENTRY']._serialized_end=278
  _globals['_APPENDRESPONSE']._serialized_start=280
  _globals['_APPENDRESPONSE']._serialized_end=309
  _globals['_QUERYREQUEST']._serialized_start=311
  _globals['_QUERYREQUEST']._serialized_end=338
  _globals['_QUERYRESPONSE']._serialized_start=340
  _globals['_QUERYRESPONSE']._serialized_end=369
  _globals['_RECALLREQUEST']._serialized_start=371
  _globals['_RECALLREQUEST']._serialized_end=411
  _globals['_SUBSCRIBEREQUEST']._serialized_start=413
  _globals['_SUBSCRIBEREQUEST']._serialized_end=449
  _globals['_EVENTMESSAGE']._serialized_start=451
  _globals['_EVENTMESSAGE']._serialized_end=500
  _globals['_SNAPSHOTREQUEST']._serialized_start=502
  _globals['_SNAPSHOTREQUEST']._serialized_end=519
  _globals['_SNAPSHOTRESPONSE']._serialized_start=521
  _globals['_SNAPSHOTRESPONSE']._serialized_end=552
  _globals['_ADMINREQUEST']._serialized_start=554
  _globals['_ADMINREQUEST']._serialized_end=593
  _globals['_ADMINRESPONSE']._serialized_start=595
  _globals['_ADMINRESPONSE']._serialized_end=639
  _globals['_HERACLITUS']._serialized_start=642
  _globals['_HERACLITUS']._serialized_end=1085
# @@protoc_insertion_point(module_scope)
